"""added ai summary field in candidate table

Revision ID: eba2aeb5a643
Revises: aa3838e8fbd9
Create Date: 2026-05-09 22:54:25.465347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba2aeb5a643'
down_revision: Union[str, Sequence[str], None] = 'aa3838e8fbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'ai_summary')
    # ### end Alembic commands ###
